<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div id="shopping-cart-table"
        data-mage-init='{ "checkout-cart": {} }'
        class="fab__cart-table__products cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <div class="page-title-wrapper">
          <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper"><?php echo __('My Bag'); ?></span>
          </h1>
          <div class="fab__cart-table__products__count">
            <?php echo $block->getItemsCount(); ?> <?php echo $block->getItemsCount() > 1 ? __('items') : __('item'); ?>
          </div>
        </div>
        <?php foreach ($block->getItems() as $_item): ?>
            <?php echo $block->getItemHtml($_item) ?>
        <?php endforeach ?>
    </div>

    <?php if($sampleItems = $block->getSampleItems()): ?>
    <div class="fab__cart-table__products _js-fabToggleContent">
        <div class="page-title-wrapper" role="_tab">
          <h1 class="page-title">
            <?php echo __('Free Samples')?>
          </h1>
        </div>
        <div class="_js-fabMobileToggled" role="_tabpanel">
          <div>
            <?php foreach($sampleItems as $sampleItem): ?>
              <?php echo $this->getItemHtml($sampleItem) ?>
            <?php endforeach; ?>
          </div>
        </div>
      </div>
    <?php endif; ?>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
<?php echo $block->getChildHtml('checkout.cart.invalidate'); ?>
