<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<div class="nav-menu">
<ul>
    <li class="nav-menu-main">
        <a data-toggle="collapse" href="#shop-nav" class="nav-toggle nav-toggled collapsed" id="shop-nav-link" aria-expanded="false">SHOP<span class="nav-toggle-icon"><i class="fa">+</i></span></a>
     
            <ul data-mage-init='{"menu":{"delay":150,"responsive":false, "expanded":false, "position":{"my":"left top","at":"left bottom"}}}'>
                    <?php /* @escapeNotVerified */ echo $_menu; ?>
                    <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
            </ul>

          
    </li>
    <!-- /// static navigation from CMS Block -->
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('side_nav')->toHtml();?>
</ul>
</div>