<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<nav class="navigation" id="nav" data-action="navigation">

    <div class="nav-menu-main">

		<div >
	    	<div >
	    		 <a href="#shop-nav" class="nav_element accordion-toggle collapse" id="shop-nav-link">SHOP</a>
	    	</div>
		</div>
		<div class="main_nav">
	        <ul data-mage-init='{"menu":{"delay":150,"responsive":false, "expanded":false, "position":{"my":"left top","at":"left bottom"}}}'>
	                <?php /* @escapeNotVerified */ echo $_menu; ?>
	                <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
	        </ul>
		</div> 
    </div>
    <!-- /// static navigation from CMS Block -->
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('side_nav')->toHtml();?>
</nav>
