<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper fab__cart">
    <a class="fab__cart__icon fab__header__top__sticky action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="fab__visually-hidden text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
        <img src="" alt="" width="22" height="28">
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <div class="fab__minicart" id="fab__minicart">
      <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart empty">
              <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: {name: getTemplate(), afterRender: function(elements) {initToggle()}} --><!-- /ko -->
              </div>
              <?php echo $block->getChildHtml('minicart.addons'); ?>
          </div>
      <?php endif ?>
    </div>
    <?php if ($promoBlockHtml = $block->getChildHtml('minicart.promo')): ?>
      <script type="text/static-block" id="minicart-promo">
        <?php echo $promoBlockHtml ?>
      </script>
    <?php endif; ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>
