<?php
/**
  * Qty and amount rendered dynamically with checkout js
  */
 ?>
<div class="fab__cart fab__cart--checkout-mobile">
  <a class="fab__cart__icon js-fabCheckoutScroll" href="#">
    <span class="counter qty">
        <span class="counter-number"><!-- void --></span>
    </span>
    <span class="counter amount">
        <span class="counter-number"><!-- void --></span>
    </span>
  </a>
</div>
