<?php
/**
  * Qty and amount rendered dynamically with checkout js
  */
 ?>
<div class="spray__cart spray__cart--checkout-mobile">
  <a class="spray__cart__icon js-sprayCheckoutScroll" href="#">
    <span class="counter qty">
        <span class="counter-number"><!-- void --></span>
    </span>
    <span class="counter amount">
        <span class="counter-number"><!-- void --></span>
    </span>
  </a>
</div>
